package:
  name: interpolation
  version: "0.1.8"

source:
  path: ../
#  git_url: https://github.com/econforge/interpolation.py
#  git_tag: v0.1.8

build:
  script: python setup.py install --single-version-externally-managed  --record=record.txt
  noarch_python: True
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numba
    - numpy
    - pandas
    - cython
    - scipy
    - tempita
    - pip

  run:
    - python
    - numba
    - numpy
    - pandas
    - cython
    - tempita
    - scipy

test:
  # Python imports
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.smolyak.tests
    - interpolation.splines
    - interpolation.splines.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2
  summary: 'Interpolation in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
