name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9']

    name: Test Interpolation.py (Python ${{ matrix.python-version }})
    steps:

      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install dependencies
        run: poetry install
      
      # - name: Code Quality
      #   run: poetry run black . --check

      - name: Test with pytest
        run: poetry run pytest
