name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    name: Test Interpolation.py (Python ${{ matrix.python-version }})
    steps:

      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install
      
      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        run: poetry run pytest
